# Generated by Django 3.0.6 on 2021-03-14 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PetFoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('fiber', models.FloatField()),
                ('ash', models.FloatField()),
                ('other', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vet', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField()),
                ('comments', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vet_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetFoodAmountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_food_diary.MealModel')),
                ('pet_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_food_diary.PetFoodModel')),
            ],
        ),
        migrations.AddField(
            model_name='mealmodel',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_food_diary.PetModel'),
        ),
        migrations.AddField(
            model_name='mealmodel',
            name='pet_food_used',
            field=models.ManyToManyField(through='pet_food_diary.PetFoodAmountModel', to='pet_food_diary.PetFoodModel'),
        ),
    ]
