# Generated by Django 3.0.6 on 2021-03-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_food_diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmodel',
            name='vet',
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
